server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Esto es vital para que las rutas de Angular (como /productos) funcionen al refrescar
        try_files $uri $uri/ /index.html;
    }

    # Eliminamos el bloque /api/ porque Angular ya sabe ir directo a Render.
    # Esto evita que Nginx dependa de otros contenedores para poder iniciar.
}