name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # Pruebas
  tests:
    name: Pruebas (Unitarias & Integración)
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Descargar código (Checkout)
      uses: actions/checkout@v3

    - name: Configurar Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test
      env:
        DB_TYPE: memory
        JWT_SECRET: ${{ secrets.JWT_SECRET || 'test_secret_key' }}
  
  # Despliegue
  deploy:
    name: Build & Push a Docker Hub
    needs: tests
    runs-on: ubuntu-latest

    # Solo corre si es la rama main (evita correr en Pull Requests)
    if: github.ref == 'refs/heads/main'

    env:
      APP_VERSION: 1.1.0

    steps:
    - name: Descargar código (Checkout)
      uses: actions/checkout@v3

    - name: Login en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/tecno-back:latest \
                      -t ${{ secrets.DOCKER_USERNAME }}/tecno-back:${{ env.APP_VERSION }} \
                      ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/tecno-back:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/tecno-back:${{ env.APP_VERSION }}

    - name: Build & Push Frontend
      run: |
        # El punto final (.) es el CONTEXTO (la raíz del proyecto)
        # -f apunta al Dockerfile que está dentro de la carpeta frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/tecno-front:latest \
                      -t ${{ secrets.DOCKER_USERNAME }}/tecno-front:${{ env.APP_VERSION }} \
                      -f frontend/Dockerfile . 
        
        docker push ${{ secrets.DOCKER_USERNAME }}/tecno-front:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/tecno-front:${{ env.APP_VERSION }}